checks:
    php:
        code_rating: true
        duplication: true

build:
    tests:
        override:
            -
                command: 'phpunit'
                coverage:
                    file: tests/reports/coverage-clover.xml
                    format: php-clover
